name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} hub.docker.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag xavierror/transmission
          # 推送镜像到镜像仓库
          docker push xavierror/transmission
